package fr.diginamic.token;

public enum SyntaxKind {
    CSV_SEPARATOR,
    ENTITY_SEPARATOR,
    END_OF_LINE_TOKEN,
    ENTITY_FIELD,
    WHITESPACE_TOKEN, BAD_TOKEN, MINUS_TOKEN, DESCRIPTOR, IGNORED_TOKEN,
}
